//! Compare the ICU4X 2.0.0 and 2.3.0 dumps and write
//! `crates/protomolt-unicode16/src/tables.rs` to standard output.
//!
//! The freeze crate restores the Unicode 16 answer for three kinds of
//! difference, and this tool refuses any other kind by name, so a new ICU4X
//! release that moves an answer the freeze does not handle stops here
//! instead of reaching persisted identities:
//!
//! - a scalar unassigned under 2.0.0 and assigned under 2.3.0: its
//!   category, script, combining class and case fold may differ, its
//!   decomposition and composition may not;
//! - a scalar whose Extended_Pictographic flag was removed;
//! - a scalar assigned under 2.0.0 whose general category changed.
//!
//! Usage: `generate <icu-2.0 dump> <icu-2.3 dump>`; see `../run.sh`.

struct Row<'a> {
    cp: u32,
    category: &'a str,
    script: &'a str,
    pictographic: &'a str,
    combining_class: &'a str,
    nfd: &'a str,
    nfc: &'a str,
    nfc_of_nfd: &'a str,
    fold: &'a str,
}

fn parse(line: &str) -> Row<'_> {
    let fields: Vec<&str> = line.split('\t').collect();
    assert_eq!(
        fields.len(),
        9,
        "dump row has {} fields: {line}",
        fields.len()
    );
    Row {
        cp: u32::from_str_radix(fields[0], 16).expect("code point is hex"),
        category: fields[1],
        script: fields[2],
        pictographic: fields[3],
        combining_class: fields[4],
        nfd: fields[5],
        nfc: fields[6],
        nfc_of_nfd: fields[7],
        fold: fields[8],
    }
}

fn same(cp: u32, what: &str, old: &str, new: &str) {
    assert_eq!(
        old, new,
        "U+{cp:04X}: {what} differs between ICU4X 2.0.0 ({old}) and 2.3.0 ({new}), \
         a difference the Unicode 16 freeze does not restore"
    );
}

fn ranges(cps: &[u32]) -> Vec<(u32, u32)> {
    let mut out: Vec<(u32, u32)> = Vec::new();
    for &cp in cps {
        match out.last_mut() {
            Some((_, end)) if *end + 1 == cp => *end = cp,
            _ => out.push((cp, cp)),
        }
    }
    out
}

fn write_ranges(name: &str, doc: &str, cps: &[u32]) {
    println!("/// {doc}");
    println!("/// {} scalars, as sorted inclusive ranges.", cps.len());
    println!("pub(crate) const {name}: &[(u32, u32)] = &[");
    for (start, end) in ranges(cps) {
        println!("    (0x{start:04X}, 0x{end:04X}),");
    }
    println!("];");
}

fn main() {
    let args: Vec<String> = std::env::args().collect();
    assert_eq!(
        args.len(),
        3,
        "usage: generate <icu-2.0 dump> <icu-2.3 dump>"
    );
    let old = std::fs::read_to_string(&args[1]).expect("read the ICU4X 2.0.0 dump");
    let new = std::fs::read_to_string(&args[2]).expect("read the ICU4X 2.3.0 dump");
    assert_eq!(
        old.lines().count(),
        1_112_064,
        "the 2.0.0 dump covers every scalar value"
    );
    assert_eq!(
        new.lines().count(),
        1_112_064,
        "the 2.3.0 dump covers every scalar value"
    );

    let mut new_in_17 = Vec::new();
    let mut pictographic_removed = Vec::new();
    let mut category_changed: Vec<(u32, String)> = Vec::new();
    for (old, new) in old.lines().zip(new.lines()) {
        let (old, new) = (parse(old), parse(new));
        assert_eq!(old.cp, new.cp, "the dumps are in the same order");
        let cp = old.cp;
        if old.pictographic != new.pictographic {
            assert!(
                old.pictographic == "1" && new.pictographic == "0",
                "U+{cp:04X}: Extended_Pictographic was added, a difference the freeze does not restore"
            );
            pictographic_removed.push(cp);
        }
        same(cp, "NFD", old.nfd, new.nfd);
        same(cp, "NFC", old.nfc, new.nfc);
        same(cp, "NFC of NFD", old.nfc_of_nfd, new.nfc_of_nfd);
        if old.category == "Unassigned" && new.category != "Unassigned" {
            new_in_17.push(cp);
            continue;
        }
        same(cp, "script", old.script, new.script);
        same(
            cp,
            "canonical combining class",
            old.combining_class,
            new.combining_class,
        );
        same(cp, "case fold", old.fold, new.fold);
        if old.category != new.category {
            category_changed.push((cp, old.category.to_string()));
        }
    }

    println!("//! Generated by tools/unicode16-freeze/run.sh from the ICU4X 2.0.0 and");
    println!("//! 2.3.0 data; do not edit by hand.");
    println!();
    println!("use icu_properties::props::GeneralCategory;");
    println!();
    write_ranges(
        "NEW_IN_UNICODE_17",
        "Scalars unassigned under ICU4X 2.0.0 (Unicode 16) and assigned under 2.3.0 (Unicode 17).",
        &new_in_17,
    );
    println!();
    write_ranges(
        "EXTENDED_PICTOGRAPHIC_REMOVED_IN_UNICODE_17",
        "Scalars with Extended_Pictographic under ICU4X 2.0.0 and without it under 2.3.0.",
        &pictographic_removed,
    );
    println!();
    println!("/// Scalars assigned under ICU4X 2.0.0 whose general category changed in 2.3.0,");
    println!("/// with the 2.0.0 category.");
    println!("pub(crate) const GENERAL_CATEGORY_IN_UNICODE_16: &[(u32, GeneralCategory)] = &[");
    for (cp, category) in &category_changed {
        println!("    (0x{cp:04X}, GeneralCategory::{category}),");
    }
    println!("];");
}
